server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cheng?serverTimezone=GMT%2b8
    username: root
    password: e23s5

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.mark.cheng
  type-handlers-package: com.mark.cheng.utils
  configuration:
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

